
    class GodAndDemonHybrid{
        constructor(name,title,homeTown,grace,commendements,weakness,health,level,specialAttack,Ability,BackupAbility){
            this.name = "Max";
            this.title = "Max the Dragon sin of wrath"
            this.homeTown = "Purgatory";
            this.grace = "sunshine";
            this.commandements = "bravery";
            this.weakness = "He can lose controll when he is angry enough and go on a rampage";
            this.health = 200,000;
            this.level = 100;
            this.specialAttack = specialAttack;
            this.Ability = "Ruler";//If he wants too he can turn off his ability and replace with his backup Ability 
            this.BackupAbility = "Dark Nebula";//
    } 
}